#!/bin/bash

#**********************************************************************************
#Author: Brian Andrews
#Last Date Modified: 10/17/2019
#**********************************************************************************

input_name=$1

#create the Ramachandran plot
gnuplot <<- EOF
  set pm3d map
  set key off
  set xtics 60 font "Helvetica,21"
  set mxtics 2
  set ytics 60 font "Helvetica,21"
  set mytics 2
  set cbtics font "Helvetica,21"
  # set grid xtics ytics
  # set grid mxtics mytics
  set object 1 rect from -180,130 to -130,180
  set object 1 fillstyle empty front clip lw 1.0  dashtype solid fc "red"
  set object 2 rect from -130,130 to -90,180
  set object 2 fillstyle empty front clip lw 1.0  dashtype solid fc "yellow"
  set object 3 rect from -90,100 to -42,180
  set object 3 fillstyle empty front clip lw 1.0  dashtype solid fc "blue"
  set object 4 rect from -90,-60 to -32,-14
  set object 4 fillstyle empty front clip lw 1.0  dashtype solid fc "green"
  set object 5 rect from -150,100 to -90,130
  set object 5 fillstyle empty front clip lw 1.0  dashtype solid fc "green"
  set palette defined (0.0 "white", 0.05 "blue",  0.15 "green", 0.3 "yellow", 0.5 "orange", 0.7 "red", 1.0 "magenta")
  set size square
  set term postscript eps enhanced solid color
  set cbrange [$2:$3]
  set xlabel "{Phi}" font "Helvetica,26" offset 0, -1
  set ylabel "{Psi}" font "Helvetica,26" offset -3, 0
  set xrange [-200:200]
  set yrange [-200:200]

  splot "${input_name}.txt" using 1:2:3 palette

  set term postscript solid color
  set output "${input_name}.eps"
  replot
EOF
